# Generated by Django 5.2.3 on 2025-07-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="qrcode_manager.basemodel",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="description"),
                ),
                ("url", models.URLField(verbose_name="url")),
                (
                    "qr_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcode", verbose_name="qrcode"
                    ),
                ),
            ],
            bases=("qrcode_manager.basemodel",),
        ),
    ]
