# Generated by Django 5.2.3 on 2025-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="qr_img",
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="url",
            field=models.URLField(unique=True, verbose_name="url"),
        ),
    ]
