# Generated by Django 5.2.3 on 2025-07-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0002_remove_qrcode_qr_img_alter_qrcode_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="filename",
            field=models.CharField(default="", max_length=100, verbose_name="filename"),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="slug",
            field=models.CharField(
                blank=True, max_length=40, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="description",
            field=models.CharField(max_length=30, verbose_name="description"),
        ),
    ]
