# Generated by Django 5.2.3 on 2025-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0003_qrcode_filename_qrcode_slug_alter_qrcode_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="last_visited",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last_visited"
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="visit_count",
            field=models.IntegerField(default=0, verbose_name="visit_count"),
        ),
    ]
