# Generated by Django 5.2.13 on 2026-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0004_qrcode_last_visited_qrcode_visit_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrcode",
            options={
                "permissions": [
                    ("create_slug_qrcode", "Can create slug-style QR codes")
                ]
            },
        ),
    ]
