# Generated by Django 5.2.13 on 2026-06-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0006_seed_qr_slug_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="back_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="back_color"
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="fill_color",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="fill_color"
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="logo_filename",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="logo_filename"
            ),
        ),
    ]
