# Generated by Django 5.2.13 on 2026-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcode_manager", "0007_qrcode_back_color_qrcode_fill_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="color_mask_style",
            field=models.CharField(
                default="solid", max_length=20, verbose_name="color_mask_style"
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="gradient_color",
            field=models.CharField(
                default="#0000ff", max_length=7, verbose_name="gradient_color"
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="module_style",
            field=models.CharField(
                default="square", max_length=20, verbose_name="module_style"
            ),
        ),
    ]
