# Generated by Django 5.2.13 on 2026-05-02 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import expenses.models
import expenses.storage

CATEGORY_NAMES = ["Food", "Lodging", "Transit", "Activities", "Shopping", "Other"]
EXPENSES_GROUP = "expenses_users"


def seed_forward(apps, schema_editor):
    """Create the predefined categories and the expenses_users group."""
    Category = apps.get_model("expenses", "Category")
    Group = apps.get_model("auth", "Group")
    for name in CATEGORY_NAMES:
        Category.objects.get_or_create(name=name)
    Group.objects.get_or_create(name=EXPENSES_GROUP)


def seed_reverse(apps, schema_editor):
    """Remove the seeded group; leave categories alone (may have FK refs)."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=EXPENSES_GROUP).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start_date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end_date"),
                ),
                (
                    "base_currency",
                    models.CharField(
                        help_text="ISO 4217 code, e.g. USD. Locked at creation; admin override only.",
                        max_length=3,
                        verbose_name="base_currency",
                    ),
                ),
                (
                    "fx_rates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Map of currency code to multiplier into base, e.g. {"JPY": 0.0067}.',
                        verbose_name="fx_rates",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="is_archived"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="display_name"
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="key"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent_at"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="accepted_at"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="expenses.event",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "expense invitation",
                "verbose_name_plural": "expense invitations",
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="invited_email",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="display_name"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        default="member",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="joined_at"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="expenses.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "id"],
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="original_amount"
                    ),
                ),
                (
                    "original_currency",
                    models.CharField(max_length=3, verbose_name="original_currency"),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed at save: original_amount * event.fx_rates[currency].",
                        max_digits=12,
                        verbose_name="base_amount",
                    ),
                ),
                ("paid_at", models.DateField(verbose_name="paid_at")),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        help_text="Encrypted at rest. Max 10 MB; jpg, png, heic, pdf.",
                        null=True,
                        storage=expenses.storage.EncryptedFileSystemStorage(),
                        upload_to=expenses.models._receipt_upload_to,
                        verbose_name="receipt",
                    ),
                ),
                (
                    "receipt_original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="receipt_original_filename",
                    ),
                ),
                (
                    "receipt_content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="receipt_content_type",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who logged this expense. Only this user (or a superuser) can delete.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="expenses.event",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_paid",
                        to="expenses.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "share_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="share_amount"
                    ),
                ),
                (
                    "reimbursed",
                    models.BooleanField(default=False, verbose_name="reimbursed"),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="expenses.expense",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shares",
                        to="expenses.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["participant__display_name"],
                "unique_together": {("expense", "participant")},
            },
        ),
        migrations.RunPython(seed_forward, seed_reverse),
    ]
