# Generated by Django 5.2.13 on 2026-05-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="payment_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="How others can pay you back — free text. e.g. 'paypal.me/alice', 'e-transfer to alice@example.com', wire details, etc. Shown to anyone who owes this participant.",
                verbose_name="payment_info",
            ),
        ),
    ]
