# Generated by Django 5.2.13 on 2026-05-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_participant_payment_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date", "-creation_date"],
                "permissions": [("access_expenses", "Can access the expenses module")],
            },
        ),
    ]
