# Generated by Django 5.2.14 on 2026-05-23 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_seed_expenses_user_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseinvitation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expenseinvitation",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="expenseinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expenseinvitation",
            name="key",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="expenseinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
