# Generated by Django 5.2.14 on 2026-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0002_seed_content_planner_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="channel",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("mastodon", "Mastodon"),
                    ("linkedin", "LinkedIn"),
                    ("x", "X / Twitter"),
                    ("instagram", "Instagram"),
                    ("newsletter", "Newsletter"),
                    ("podcast", "Podcast"),
                    ("talk", "Talk"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
