# Generated by Django 5.2.14 on 2026-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0003_alter_post_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="expected_asset",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What asset this post needs, e.g. “hero image” or “square graphic”. Leave blank if none. Flagged as missing until an asset is attached.",
                max_length=200,
            ),
        ),
    ]
