# Generated by Django 5.2.14 on 2026-06-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0004_post_expected_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="expected_asset",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Assets this post needs, one per line (e.g. “hero image”, “square graphic”). Flagged as missing until that many assets are attached. Leave blank if none.",
            ),
        ),
    ]
