# Generated by Django 5.2.14 on 2026-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0005_alter_post_expected_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="hashtags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default hashtags for this campaign's social posts, e.g. “#PyLadiesCon #Python”. Appended when you copy a social post.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Extra hashtags for this post, added to the campaign's defaults. Appended when you copy a social post.",
                max_length=255,
            ),
        ),
    ]
