# Generated by Django 6.0.6 on 2026-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0006_campaign_hashtags_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="channel",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("mastodon", "Mastodon"),
                    ("bluesky", "Bluesky"),
                    ("linkedin", "LinkedIn"),
                    ("x", "X / Twitter"),
                    ("instagram", "Instagram"),
                    ("newsletter", "Newsletter"),
                    ("podcast", "Podcast"),
                    ("talk", "Talk"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
