# Generated by Django 6.0.6 on 2026-07-23 00:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("content_planner", "0007_alter_post_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MastodonApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("instance_host", models.CharField(max_length=255, unique=True)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", core.encryption.EncryptedTextField()),
            ],
            options={
                "ordering": ["instance_host"],
            },
        ),
        migrations.CreateModel(
            name="PublishingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("bluesky", "Bluesky"),
                            ("mastodon", "Mastodon"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        help_text="Stable remote identity: did:plc:… / account id / ig-user-id.",
                        max_length=255,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="Display only. Handles change; remote_id does not.",
                        max_length=255,
                    ),
                ),
                (
                    "instance_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Mastodon host, or Bluesky PDS.",
                    ),
                ),
                (
                    "access_token",
                    core.encryption.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "refresh_token",
                    core.encryption.EncryptedTextField(blank=True, default=""),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("needs_reauth", "Needs reconnecting"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached platform facts: instance char limit, IG page id, etc.",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publishing_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["platform", "handle"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(db_index=True, help_text="UTC."),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("remote_id", models.CharField(blank=True, default="", max_length=512)),
                ("remote_url", models.URLField(blank=True, default="")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set after a transient failure; the dispatcher skips the row until then.",
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connector scratch space, e.g. an Instagram container id.",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="content_planner.post",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content_planner.publishingaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.AddConstraint(
            model_name="publishingaccount",
            constraint=models.UniqueConstraint(
                fields=("owner", "platform", "remote_id"),
                name="uniq_publishing_account",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["state", "scheduled_for"], name="content_pla_state_1d77ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "sent")),
                fields=("post", "account"),
                name="one_success_per_target",
            ),
        ),
    ]
