# Generated by Django 5.2.13 on 2026-04-21 22:30

import django.db.models.deletion
import timezone_field.fields
from django.db import migrations, models

import availability.encryption
import availability.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailabilityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        default="America/Vancouver",
                        use_pytz=False,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "business_hours",
                    models.JSONField(
                        default=availability.models._default_business_hours,
                        verbose_name="business_hours",
                    ),
                ),
                (
                    "extended_hours",
                    models.JSONField(
                        default=availability.models._default_extended_hours,
                        verbose_name="extended_hours",
                    ),
                ),
                (
                    "default_slot_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="default_slot_minutes"
                    ),
                ),
                (
                    "min_notice_hours",
                    models.PositiveIntegerField(
                        default=12, verbose_name="min_notice_hours"
                    ),
                ),
                (
                    "max_horizon_days",
                    models.PositiveIntegerField(
                        default=21, verbose_name="max_horizon_days"
                    ),
                ),
                (
                    "extended_reveal_threshold",
                    models.PositiveIntegerField(
                        default=4, verbose_name="extended_reveal_threshold"
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("label", models.CharField(max_length=50, verbose_name="label")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "refresh_token",
                    availability.encryption.EncryptedTextField(
                        blank=True, default="", verbose_name="refresh_token"
                    ),
                ),
                (
                    "scopes_granted",
                    models.JSONField(default=list, verbose_name="scopes_granted"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                (
                    "google_calendar_id",
                    models.CharField(max_length=255, verbose_name="google_calendar_id"),
                ),
                (
                    "display_label",
                    models.CharField(max_length=100, verbose_name="display_label"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_calendars",
                        to="availability.googleaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "google_calendar_id")},
            },
        ),
    ]
