# Generated by Django 5.2.13 on 2026-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityprofile",
            name="meeting_buffer_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Padding applied before and after every busy block when computing free slots. 30 minutes by default.",
                verbose_name="meeting_buffer_minutes",
            ),
        ),
    ]
