# Generated by Django 5.2.13 on 2026-05-06 15:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qrcode_manager", "0006_seed_qr_slug_user_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rating", "Rating"),
                            ("multi_select", "Multi-select"),
                            ("nps", "NPS"),
                            ("open_text", "Open text"),
                            ("yes_no", "Yes / no"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="config"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="order")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="submission_uuid"
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="value")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted_at"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.question",
                    ),
                ),
            ],
            options={
                "ordering": ["submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_representative",
                    models.BooleanField(
                        default=False, verbose_name="is_representative"
                    ),
                ),
                (
                    "tagged_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="tagged_at"),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.response",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="response_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tagged_at"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "short_url",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey",
                        to="qrcode_manager.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.survey",
            ),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="modified_date"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "tag",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="tag"
                    ),
                ),
                (
                    "action_item",
                    models.TextField(
                        blank=True, default="", verbose_name="action_item"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "responses",
                    models.ManyToManyField(
                        related_name="themes",
                        through="surveys.ResponseTheme",
                        to="surveys.response",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["survey", "name"],
            },
        ),
        migrations.AddField(
            model_name="responsetheme",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.theme"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["submission_uuid"], name="surveys_res_submiss_c23e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["question", "submitted_at"],
                name="surveys_res_questio_2e4350_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("survey", "order"),
                name="surveys_question_unique_order_per_survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("survey", "name"), name="surveys_theme_unique_name_per_survey"
            ),
        ),
        migrations.AddConstraint(
            model_name="responsetheme",
            constraint=models.UniqueConstraint(
                fields=("response", "theme"),
                name="surveys_responsetheme_unique_response_theme",
            ),
        ),
        migrations.AddConstraint(
            model_name="responsetheme",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_representative", True)),
                fields=("theme",),
                name="surveys_responsetheme_one_representative_per_theme",
            ),
        ),
    ]
