# Generated by Django 5.2.13 on 2026-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True, verbose_name="required"),
        ),
    ]
