# Generated by Django 5.2.13 on 2026-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_extract_required_from_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="is_flagged",
            field=models.BooleanField(default=False, verbose_name="is_flagged"),
        ),
    ]
