# Generated by Django 5.2.13 on 2026-05-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_migrate_flag_theme_to_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["-creation_date"],
                "permissions": [("access_surveys", "Can access the surveys module")],
            },
        ),
    ]
