# Generated by Django 5.2.13 on 2026-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0009_seed_collaborator_group_and_create_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="description"
            ),
        ),
    ]
