# Generated by Django 5.2.14 on 2026-05-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_survey_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="is_flagged",
        ),
    ]
